-- Migrate control catalog from legacy CMMC 1.0-style IDs to NIST SP 800-171 Rev 2 IDs
-- Generated by scripts/build-catalog.mjs — do not edit by hand.
--
-- 1. Insert the 110 NIST SP 800-171 Rev 2 requirements with DoD Assessment
--    Methodology weights (1/3/5; 3.12.4 has weight 0 = special SSP rule).
-- 2. Remap control_id in all child tables from legacy IDs.
-- 3. Remove the legacy control rows.

insert into controls (id, domain, domain_code, level, description, weight, guidance) values
  ('3.1.1', 'Access Control', 'AC', 1, 'Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).', 5, 'Create and maintain a documented list of authorized users and devices. Implement Active Directory or a similar identity management system to enforce access controls. Remove access immediately when users leave or change roles.'),
  ('3.1.2', 'Access Control', 'AC', 1, 'Limit system access to the types of transactions and functions that authorized users are permitted to execute.', 5, 'Define and document user roles with specific permissions for each system. Use role-based access control (RBAC) to limit what each user can do. Review and update role assignments quarterly.'),
  ('3.1.3', 'Access Control', 'AC', 2, 'Control the flow of CUI in accordance with approved authorizations.', 1, 'Document all locations and systems where CUI flows. Implement data loss prevention (DLP) tools or network segmentation to restrict CUI movement to approved paths only.'),
  ('3.1.4', 'Access Control', 'AC', 2, 'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.', 1, 'Separate duties for critical functions — no single person should control an entire sensitive process end-to-end. For example, the person who approves purchases should not also process payments.'),
  ('3.1.5', 'Access Control', 'AC', 2, 'Employ the principle of least privilege, including for specific security functions and privileged accounts.', 3, 'Audit all user accounts and remove unnecessary administrative privileges. Implement a privileged access management (PAM) solution. Ensure users work with standard accounts daily and only escalate when needed.'),
  ('3.1.6', 'Access Control', 'AC', 2, 'Use non-privileged accounts or roles when accessing nonsecurity functions', 1, 'Configure all users to log in with non-privileged accounts for daily tasks. Separate admin accounts should be used only for administrative functions. Document this separation policy.'),
  ('3.1.7', 'Access Control', 'AC', 2, 'Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.', 1, 'Configure systems to prevent standard users from running privileged commands (e.g., via sudo restrictions or Group Policy). Enable audit logging for any privileged function execution.'),
  ('3.1.8', 'Access Control', 'AC', 2, 'Limit unsuccessful logon attempts.', 1, 'Configure account lockout after 3–5 failed login attempts. Set a lockout duration of at least 15 minutes or require admin unlock. Apply this to all systems including VPN and email.'),
  ('3.1.9', 'Access Control', 'AC', 2, 'Provide privacy and security notices consistent with applicable CUI rules.', 1, 'Display a privacy and security notice banner on all system login screens. The notice must reference CUI handling requirements. Use your organization''s approved banner text or adopt NIST-recommended language.'),
  ('3.1.10', 'Access Control', 'AC', 2, 'Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity', 1, 'Enable screen lock on all workstations after 15 minutes of inactivity with a pattern-hiding screensaver. Enforce this via Group Policy or endpoint management. Require password to unlock.'),
  ('3.1.11', 'Access Control', 'AC', 2, 'Terminate (automatically) a user session after a defined condition.', 1, 'Configure automatic session termination after a defined inactivity period (e.g., 30 minutes). Apply to all remote access sessions, web applications, and VPN connections.'),
  ('3.1.12', 'Access Control', 'AC', 2, 'Monitor and control remote access sessions.', 5, 'Deploy a VPN solution with logging enabled for all remote sessions. Review remote access logs weekly. Ensure remote sessions can be terminated by administrators if needed.'),
  ('3.1.13', 'Access Control', 'AC', 2, 'Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.', 5, 'Require TLS 1.2 or higher for all remote access sessions. Disable older protocols (SSL, TLS 1.0/1.1). Use a VPN with AES-256 encryption for all remote connections to company systems.'),
  ('3.1.14', 'Access Control', 'AC', 2, 'Route remote access via managed access control points.', 1, 'Route all remote access through a centrally managed VPN gateway or jump server. Do not allow direct remote desktop connections to internal systems from the internet.'),
  ('3.1.15', 'Access Control', 'AC', 2, 'Authorize remote execution of privileged commands and remote access to security-relevant information.', 1, 'Document any operational need for privileged commands over remote access. Restrict remote privileged execution to named, approved users only. Log all such activity.'),
  ('3.1.16', 'Access Control', 'AC', 2, 'Authorize wireless access prior to allowing such connections', 5, 'Maintain a documented list of authorized wireless access points. Use 802.1X authentication to ensure only authorized devices connect to Wi-Fi. Conduct periodic wireless scans to detect rogue access points.'),
  ('3.1.17', 'Access Control', 'AC', 2, 'Protect wireless access using authentication and encryption', 5, 'Secure all Wi-Fi networks with WPA3 or WPA2-Enterprise with AES encryption. Disable WEP and TKIP. Use a separate guest network that is isolated from systems handling CUI.'),
  ('3.1.18', 'Access Control', 'AC', 2, 'Control connection of mobile devices.', 5, 'Implement a mobile device management (MDM) solution such as Microsoft Intune or Jamf. Require enrollment before any mobile device accesses company resources. Define and enforce an acceptable use policy for mobile devices.'),
  ('3.1.19', 'Access Control', 'AC', 2, 'Encrypt CUI on mobile devices and mobile computing platforms.', 3, 'Enable full-disk encryption on all mobile devices and laptops (e.g., BitLocker for Windows, FileVault for Mac). Enforce this via MDM policy. Verify encryption status on all managed devices.'),
  ('3.1.20', 'Access Control', 'AC', 1, 'Verify and control/limit connections to and use of external systems.', 1, 'Document all connections to external systems (cloud providers, partners, vendors). Review and reauthorize these connections annually. Implement firewall rules to restrict which external systems can connect to your network.'),
  ('3.1.21', 'Access Control', 'AC', 2, 'Limit use of portable storage devices on external systems.', 1, 'Implement a policy prohibiting the use of personal USB drives and external storage on company systems. Use endpoint management software (e.g., Microsoft Intune) to block unauthorized portable storage.'),
  ('3.1.22', 'Access Control', 'AC', 1, 'Control CUI posted or processed on publicly accessible systems.', 1, 'Establish a review process before posting any information to public-facing websites. Ensure CUI is never posted publicly. Designate a responsible individual to approve all public content.'),
  ('3.2.1', 'Awareness and Training', 'AT', 2, 'Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.', 5, 'Conduct annual security awareness training for all personnel. Cover CUI handling, phishing recognition, password hygiene, and acceptable use policies. Document completion with signed acknowledgments.'),
  ('3.2.2', 'Awareness and Training', 'AT', 2, 'Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.', 5, 'Provide role-specific training for personnel with security responsibilities (e.g., system admins, incident responders). Training should cover their specific duties and be completed before granting elevated access.'),
  ('3.2.3', 'Awareness and Training', 'AT', 2, 'Provide security awareness training on recognizing and reporting potential indicators of insider threat.', 1, 'Include phishing simulation training in your security awareness program. Send simulated phishing emails quarterly and provide immediate training to those who click. Train staff to report suspicious emails.'),
  ('3.3.1', 'Audit and Accountability', 'AU', 2, 'Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity', 5, 'Configure centralized log collection (e.g., a SIEM or log server). Retain logs for at least 90 days online and 1 year in archive. Ensure logs capture logins, file access, and system changes.'),
  ('3.3.2', 'Audit and Accountability', 'AU', 2, 'Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions.', 3, 'Enable user activity logging on all systems that handle CUI. Ensure logs capture username, timestamp, and action taken. Use a unique identifier for each user — no shared accounts.'),
  ('3.3.3', 'Audit and Accountability', 'AU', 2, 'Review and update logged events.', 1, 'Review your audit logging configuration quarterly. Update logged event types when systems change. Ensure newly added systems and applications are included in your logging policy.'),
  ('3.3.4', 'Audit and Accountability', 'AU', 2, 'Alert in the event of an audit logging process failure.', 1, 'Configure automated alerts for audit log failures (e.g., disk full, service stopped). Test alerting annually. Designate a responsible person to respond to log failure notifications.'),
  ('3.3.5', 'Audit and Accountability', 'AU', 2, 'Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.', 5, 'Implement a SIEM solution or log aggregation tool to correlate events across systems. Establish a process for investigating flagged events. Document your analysis and response procedures.'),
  ('3.3.6', 'Audit and Accountability', 'AU', 2, 'Provide audit record reduction and report generation to support on-demand analysis and reporting.', 1, 'Deploy a log management tool that supports filtering, searching, and report generation. Ensure authorized personnel can query logs on demand. Test report generation capability quarterly.'),
  ('3.3.7', 'Audit and Accountability', 'AU', 2, 'Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records', 1, 'Configure all systems to sync their clocks with an authoritative NTP server (e.g., time.nist.gov). Verify NTP synchronization is working on all servers and workstations. Document your time synchronization policy.'),
  ('3.3.8', 'Audit and Accountability', 'AU', 2, 'Protect audit information and audit logging tools from unauthorized access, modification, and deletion.', 1, 'Restrict access to audit logs to security administrators only. Store logs in a write-once or tamper-evident system. Back up logs separately from the systems they monitor.'),
  ('3.3.9', 'Audit and Accountability', 'AU', 2, 'Limit management of audit logging functionality to a subset of privileged users.', 1, 'Establish a weekly log review process. Use your SIEM or log tool to flag anomalies such as after-hours logins, failed access attempts, and unusual data transfers. Document findings and corrective actions.'),
  ('3.4.1', 'Configuration Management', 'CM', 2, 'Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.', 5, 'Create and maintain a complete inventory of all hardware, software, and firmware in your environment. Use an asset management tool. Review and update the inventory quarterly and whenever changes occur.'),
  ('3.4.2', 'Configuration Management', 'CM', 2, 'Establish and enforce security configuration settings for information technology products employed in organizational systems.', 5, 'Implement security hardening benchmarks (e.g., CIS Benchmarks) for all operating systems and applications. Use a configuration management tool to enforce and audit settings. Document your baseline configurations.'),
  ('3.4.3', 'Configuration Management', 'CM', 2, 'Track, review, approve or disapprove, and log changes to organizational systems.', 1, 'Establish a change management process requiring documented approval before any system change. Maintain a change log with dates, descriptions, and approver names. Review the change log monthly.'),
  ('3.4.4', 'Configuration Management', 'CM', 2, 'Analyze the security impact of changes prior to implementation.', 1, 'Require a security impact analysis before implementing any system change. Document the analysis and approver sign-off. Include this step in your change management workflow.'),
  ('3.4.5', 'Configuration Management', 'CM', 2, 'Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.', 5, 'Define and document who is authorized to make changes to systems. Implement access controls so only authorized personnel can modify system configurations. Review authorization lists quarterly.'),
  ('3.4.6', 'Configuration Management', 'CM', 2, 'Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.', 5, 'Maintain a complete, current inventory of all information systems including their purpose, owner, and location. Use automated discovery tools to identify undocumented systems. Review the inventory monthly.'),
  ('3.4.7', 'Configuration Management', 'CM', 2, 'Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.', 5, 'Disable or uninstall all software, services, ports, and protocols not required for business operations. Use a firewall to block unused ports. Document all enabled services with business justification.'),
  ('3.4.8', 'Configuration Management', 'CM', 2, 'Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.', 5, 'Implement application whitelisting (e.g., Windows Defender Application Control or AppLocker) to allow only approved software to run. Alternatively, maintain and enforce a software blacklist. Review and update the list quarterly.'),
  ('3.4.9', 'Configuration Management', 'CM', 2, 'Control and monitor user-installed software.', 1, 'Schedule annual penetration testing by a qualified third party. Use automated vulnerability scanners (e.g., Nessus, Qualys) for quarterly scans. Document findings and remediate within defined timeframes.'),
  ('3.5.1', 'Identification and Authentication', 'IA', 1, 'Identify system users, processes acting on behalf of users, and devices.', 5, 'Ensure every user, device, and process has a unique identifier. Eliminate shared accounts. Maintain a current list of all system identifiers and their associated owner.'),
  ('3.5.2', 'Identification and Authentication', 'IA', 1, 'Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.', 5, 'Implement password authentication at minimum for all system access. Verify that all systems require authentication before granting access. Remove or disable any anonymous access points.'),
  ('3.5.3', 'Identification and Authentication', 'IA', 2, 'Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts..', 5, 'Deploy multi-factor authentication (MFA) for all privileged accounts and all network access by non-privileged users. Use an authenticator app (e.g., Microsoft Authenticator) or hardware token. Disable SMS-only MFA for privileged accounts.'),
  ('3.5.4', 'Identification and Authentication', 'IA', 2, 'Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.', 1, 'Implement MFA or certificate-based authentication to prevent replay attacks. Ensure authentication tokens have short expiration times. Use modern authentication protocols (OAuth 2.0, SAML) that include replay protections.'),
  ('3.5.5', 'Identification and Authentication', 'IA', 2, 'Prevent reuse of identifiers for a defined period.', 1, 'Use mutual TLS (mTLS) or certificate-based authentication for system-to-system connections where required. Document all system interconnections and their authentication methods.'),
  ('3.5.6', 'Identification and Authentication', 'IA', 2, 'Disable identifiers after a defined period of inactivity.', 1, 'Configure accounts to be automatically disabled after 90 days of inactivity. Run a monthly report of inactive accounts and disable or remove them. Apply this to all user and service accounts.'),
  ('3.5.7', 'Identification and Authentication', 'IA', 2, 'Enforce a minimum password complexity and change of characters when new passwords are created.', 1, 'Enforce a password policy requiring minimum 12 characters, uppercase, lowercase, numbers, and special characters. Implement this via Active Directory Group Policy or your identity provider. Reject common passwords.'),
  ('3.5.8', 'Identification and Authentication', 'IA', 2, 'Prohibit password reuse for a specified number of generations.', 1, 'Configure your identity system to remember at least the last 5 passwords and prevent reuse. Apply this policy to all user accounts including service accounts.'),
  ('3.5.9', 'Identification and Authentication', 'IA', 2, 'Allow temporary password use for system logons with an immediate change to a permanent password.', 1, 'Configure systems to require users to change temporary passwords at first login. Set temporary passwords to expire within 24 hours. Apply this to all new account creations and password resets.'),
  ('3.5.10', 'Identification and Authentication', 'IA', 2, 'Store and transmit only cryptographically-protected passwords.', 5, 'Ensure all passwords are stored using strong cryptographic hashing (e.g., bcrypt, PBKDF2). Verify your identity systems and applications never store passwords in plain text. Transmit passwords only over encrypted connections (TLS).'),
  ('3.5.11', 'Identification and Authentication', 'IA', 2, 'Obscure feedback of authentication information', 1, 'Verify that all login forms mask password characters as they are typed. Ensure no system displays passwords in clear text on screen or in logs. Test this on all applications.'),
  ('3.6.1', 'Incident response', 'IR', 2, 'Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities.', 5, 'Develop and document a written incident response plan covering preparation, detection, containment, recovery, and post-incident review. Train all relevant staff on the plan. Review and update it annually.'),
  ('3.6.2', 'Incident response', 'IR', 2, 'Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization.', 5, 'Establish a process for logging all security incidents with timestamps, descriptions, and actions taken. Define which incidents must be reported externally (e.g., to DoD) and within what timeframe. Test the reporting chain annually.'),
  ('3.6.3', 'Incident response', 'IR', 2, 'Test the organizational incident response capability.', 1, 'Conduct at least annual incident response exercises or tabletop simulations. Test your ability to detect, contain, and recover from common attack scenarios. Document lessons learned and update your IR plan accordingly.'),
  ('3.7.1', 'Maintenance', 'MA', 2, 'Perform maintenance on organizational systems..', 3, 'Establish a regular maintenance schedule for all systems (operating system patches, hardware firmware, application updates). Document all maintenance activities with dates and technician names.'),
  ('3.7.2', 'Maintenance', 'MA', 2, 'Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.', 5, 'Maintain a list of approved maintenance tools and authorized maintenance personnel. Require documentation for all maintenance activities. Prohibit unapproved tools from being used on systems handling CUI.'),
  ('3.7.3', 'Maintenance', 'MA', 2, 'Ensure equipment removed for off-site maintenance is sanitized of any CUI.', 1, 'Before sending any equipment off-site for maintenance, securely wipe or remove all storage containing CUI. Document the sanitization process. If sanitization is not possible, require the maintenance provider to sign a CUI handling agreement.'),
  ('3.7.4', 'Maintenance', 'MA', 2, 'Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.', 3, 'Before using any removable media (USB drives, CDs) for maintenance or diagnostics, scan them for malware using an updated antivirus tool. Document the scan results. Never use personal media on company systems.'),
  ('3.7.5', 'Maintenance', 'MA', 2, 'Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.', 5, 'Require MFA for all remote maintenance sessions. Terminate remote maintenance connections immediately upon completion. Log all remote maintenance sessions including who connected, when, and what was done.'),
  ('3.7.6', 'Maintenance', 'MA', 2, 'Supervise the maintenance activities of maintenance personnel without required access authorization.', 1, 'When maintenance personnel lack the necessary clearance, require an authorized employee to supervise all maintenance activities. Document supervision with a sign-off log. Never leave unsupervised access to systems handling CUI.'),
  ('3.8.1', 'Media Protection', 'MP', 2, 'Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.', 3, 'Store all physical and digital media containing CUI in locked, access-controlled storage. Maintain a log of who accesses stored media. Conduct quarterly audits of media inventory.'),
  ('3.8.2', 'Media Protection', 'MP', 2, 'Limit access to CUI on system media to authorized users', 3, 'Apply sanitization methods appropriate to the sensitivity of the data. Use DoD 5220.22-M wiping for magnetic media or physical destruction for highest sensitivity. Document the method used and verify completion.'),
  ('3.8.3', 'Media Protection', 'MP', 1, 'Sanitize or destroy system media containing CUI before disposal or release for reuse.', 5, 'Establish a media sanitization policy. Before disposing of or reusing any storage media (hard drives, USB drives, paper), apply appropriate sanitization (NIST SP 800-88 methods). Document all sanitization activities.'),
  ('3.8.4', 'Media Protection', 'MP', 2, 'Mark media with necessary CUI markings and distribution limitations.', 1, 'Establish and apply a CUI marking policy. All media containing CUI must be labeled with the appropriate CUI designation. Train staff on marking requirements using the CUI Registry guidelines.'),
  ('3.8.5', 'Media Protection', 'MP', 2, 'Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.', 1, 'Implement a check-out/check-in system for all media containing CUI. Encrypt digital media during transport. Require tamper-evident packaging for physical media shipments.'),
  ('3.8.6', 'Media Protection', 'MP', 2, 'Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.', 1, 'Encrypt all portable digital media containing CUI using FIPS 140-2 validated encryption (e.g., BitLocker with TPM, VeraCrypt). Verify encryption before data is placed on the media.'),
  ('3.8.7', 'Media Protection', 'MP', 2, 'Control the use of removable media on system components.', 5, 'Use endpoint management software to control which removable media devices can connect to company computers. Block unauthorized USB devices via Group Policy or MDM. Maintain a list of approved devices.'),
  ('3.8.8', 'Media Protection', 'MP', 2, 'Prohibit the use of portable storage devices when such devices have no identifiable owner.', 3, 'Implement a policy prohibiting use of any portable storage device without an identifiable, authorized owner. Enforce via technical controls (endpoint management) and employee policy. Confiscate and safely dispose of any unidentified media found.'),
  ('3.8.9', 'Media Protection', 'MP', 2, 'Protect the confidentiality of backup CUI at storage locations.', 1, 'Encrypt all CUI in transit using TLS 1.2 or higher. Verify encryption is enforced for email (use S/MIME or a secure email gateway), file transfers (SFTP/FTPS), and any other transmission method.'),
  ('3.9.1', 'Personnel Security', 'PS', 2, 'Screen individuals prior to authorizing access to organizational systems containing CUI.', 3, 'Establish a personnel screening process for all individuals who will access CUI systems. At minimum, conduct background checks before granting access. Document screening results and maintain records.'),
  ('3.9.2', 'Personnel Security', 'PS', 2, 'Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers', 5, 'Implement a formal offboarding process that immediately revokes system access upon termination or transfer. Recover company devices and media. Conduct an exit interview covering CUI handling obligations. Document the process completion.'),
  ('3.10.1', 'Physical Protection', 'PE', 1, 'Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.', 5, 'Implement physical access controls (key cards, PIN pads, or locks) for all areas where CUI systems are located. Maintain a list of authorized individuals. Review access rights quarterly.'),
  ('3.10.2', 'Physical Protection', 'PE', 2, 'Protect and monitor the physical facility and support infrastructure for organizational systems.', 5, 'Require all visitors to sign in and be escorted by an authorized employee at all times. Maintain a visitor log with name, purpose, date/time in and out. Review the log monthly.'),
  ('3.10.3', 'Physical Protection', 'PE', 1, 'Escort visitors and monitor visitor activity.', 1, 'Ensure visitors are escorted at all times in areas where CUI is processed or stored. Brief escorts on their responsibilities. Post signage in secure areas indicating escort requirements.'),
  ('3.10.4', 'Physical Protection', 'PE', 1, 'Maintain audit logs of physical access.', 1, 'Implement an electronic or paper-based physical access log for all secure areas. Retain access logs for at least 90 days. Review logs monthly for unusual access patterns.'),
  ('3.10.5', 'Physical Protection', 'PE', 1, 'Control and manage physical access devices.', 1, 'Maintain an inventory of all physical access devices (key cards, fobs, keys). Disable or reprogram access devices immediately when employees leave. Conduct quarterly audits of access device inventory.'),
  ('3.10.6', 'Physical Protection', 'PE', 2, 'Enforce safeguarding measures for CUI at alternate work sites.', 1, 'Develop a policy for employees working remotely or at alternate sites with CUI. Require a private, lockable workspace, encrypted devices, and VPN use. Conduct periodic spot checks or attestations.'),
  ('3.11.1', 'Risk Assessment', 'RA', 2, 'Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI', 3, 'Conduct a formal risk assessment at least annually covering all systems that process, store, or transmit CUI. Document identified risks, likelihood, impact, and planned mitigations. Have leadership review and approve the assessment.'),
  ('3.11.2', 'Risk Assessment', 'RA', 2, 'Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.', 5, 'Deploy an automated vulnerability scanner (e.g., Tenable Nessus, Qualys) and run scans at least monthly. Prioritize and remediate critical and high vulnerabilities within 30 days. Document scan results and remediation actions.'),
  ('3.11.3', 'Risk Assessment', 'RA', 2, 'Remediate vulnerabilities in accordance with risk assessments.', 1, 'Establish a risk management process with defined risk categories, scoring criteria, and risk tolerance thresholds. Prioritize risks based on potential impact to CUI. Review and update risk rankings quarterly.'),
  ('3.12.1', 'Security Assessment', 'CA', 2, 'Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.', 5, 'Conduct formal security control assessments at least annually. Use NIST SP 800-171A assessment procedures as a guide. Document findings and track remediation progress.'),
  ('3.12.2', 'Security Assessment', 'CA', 2, 'Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.', 3, 'Develop a Plan of Action and Milestones (POA&M) for every identified security deficiency. Include responsible owner, planned remediation steps, and target completion date. Review POA&M progress monthly.'),
  ('3.12.3', 'Security Assessment', 'CA', 2, 'Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.', 5, 'Implement continuous monitoring for your security controls. Use automated tools where possible (e.g., vulnerability scanners, SIEM alerts). Review monitoring results monthly and update your risk posture accordingly.'),
  ('3.12.4', 'Security Assessment', 'CA', 2, 'Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.', 0, 'Develop and maintain a System Security Plan (SSP) describing your system boundaries, security requirements implementation, and external connections. Review and update the SSP annually or after significant changes.'),
  ('3.13.1', 'System and Communications Protection', 'SC', 1, 'Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.', 5, 'Deploy a next-generation firewall at all network boundaries. Configure it to inspect and log all inbound and outbound traffic. Review firewall rules quarterly and remove unnecessary rules.'),
  ('3.13.2', 'System and Communications Protection', 'SC', 2, 'Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.', 5, 'Apply security engineering principles during system design and procurement. Use the principle of least privilege, defense in depth, and fail-safe defaults. Document security requirements in all new system specifications.'),
  ('3.13.3', 'System and Communications Protection', 'SC', 2, 'Separate user functionality from system management functionality.', 1, 'Separate user-facing applications from administrative interfaces. Do not expose system management functions (admin consoles, APIs) to general users. Use separate networks or authentication for management access.'),
  ('3.13.4', 'System and Communications Protection', 'SC', 2, 'Prevent unauthorized and unintended information transfer via shared system resources.', 1, 'Configure operating systems and hypervisors to prevent information leakage between processes and virtual machines. Implement memory protection and process isolation. Review shared resource configurations quarterly.'),
  ('3.13.5', 'System and Communications Protection', 'SC', 1, 'Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.', 5, 'Implement network segmentation to isolate publicly accessible systems (web servers, email gateways) from internal systems handling CUI. Use a DMZ architecture with a firewall between each zone.'),
  ('3.13.6', 'System and Communications Protection', 'SC', 2, 'Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).', 5, 'Configure all firewalls and network devices with a default-deny rule. Explicitly permit only required traffic. Review and document all allowed traffic flows. Audit firewall rules quarterly.'),
  ('3.13.7', 'System and Communications Protection', 'SC', 2, 'Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling).', 1, 'Disable split tunneling on all VPN configurations. Require all remote traffic to route through the corporate VPN gateway. Verify VPN configuration on all remote access clients.'),
  ('3.13.8', 'System and Communications Protection', 'SC', 2, 'Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.', 3, 'Encrypt all CUI in transit using TLS 1.2 or higher or IPsec. Verify encryption is enforced across all communication channels. Use certificate pinning for sensitive application connections.'),
  ('3.13.9', 'System and Communications Protection', 'SC', 2, 'Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.', 1, 'Configure network sessions to terminate after 30 minutes of inactivity. Apply this to VPN sessions, web application sessions, and remote desktop connections. Test timeout behavior on all systems.'),
  ('3.13.10', 'System and Communications Protection', 'SC', 2, 'Establish and manage cryptographic keys for cryptography employed in organizational systems.', 1, 'Implement a key management process documenting how cryptographic keys are generated, stored, rotated, and revoked. Use a hardware security module (HSM) or key management service for production keys. Rotate keys at least annually.'),
  ('3.13.11', 'System and Communications Protection', 'SC', 2, 'Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.', 5, 'Deploy only FIPS 140-2 validated cryptographic modules for protecting CUI. Verify that encryption tools and VPNs use validated algorithms (AES-256, SHA-256, RSA-2048+). Replace non-compliant tools.'),
  ('3.13.12', 'System and Communications Protection', 'SC', 2, 'Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device..', 1, 'Disable remote activation of cameras, microphones, and screen sharing on all systems unless actively in use. Configure collaboration tools (Teams, Zoom) to indicate when recording is active. Document your policy.'),
  ('3.13.13', 'System and Communications Protection', 'SC', 2, 'Control and monitor the use of mobile code.', 1, 'Inventory all uses of mobile code (JavaScript, ActiveX, Java applets) in your environment. Restrict execution to approved, signed mobile code only. Block unsigned or unapproved mobile code via browser policy and application controls.'),
  ('3.13.14', 'System and Communications Protection', 'SC', 2, 'Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.', 1, 'If VoIP is used, implement a separate VLAN for voice traffic. Ensure VoIP traffic is encrypted (SRTP). Monitor VoIP systems for unauthorized devices and unusual call patterns. Document your VoIP security configuration.'),
  ('3.13.15', 'System and Communications Protection', 'SC', 2, 'Protect the authenticity of communications sessions.', 5, 'Require SSH or TLS-encrypted sessions for all network device management (switches, routers, firewalls). Disable Telnet and HTTP management interfaces. Change default credentials on all network devices.'),
  ('3.13.16', 'System and Communications Protection', 'SC', 2, 'Protect the confidentiality of CUI at rest.', 1, 'Audit all cryptographic implementations to ensure only government-approved algorithms are used (AES, SHA-2, RSA, ECDSA). Remove or replace any use of MD5, SHA-1, DES, or RC4. Document approved cryptographic standards.'),
  ('3.14.1', 'System and Information Integrity', 'SI', 1, 'Identify, report, and correct system flaws in a timely manner.', 5, 'Establish a patch management process. Subscribe to vendor security advisories for all software in use. Apply critical patches within 30 days and high patches within 60 days. Document all patching activities.'),
  ('3.14.2', 'System and Information Integrity', 'SI', 1, 'Provide protection from malicious code at designated locations within organizational systems.', 5, 'Deploy endpoint protection (antivirus/EDR) on all workstations and servers. Configure real-time scanning and automatic signature updates. Ensure protection software cannot be disabled by end users.'),
  ('3.14.3', 'System and Information Integrity', 'SI', 2, 'Monitor system security alerts and advisories and take action in response.', 5, 'Deploy an intrusion detection system (IDS) or SIEM to monitor for attacks and unauthorized connections. Configure alerts for suspicious activity. Review alerts daily and document your response to each alert.'),
  ('3.14.4', 'System and Information Integrity', 'SI', 1, 'Update malicious code protection mechanisms when new releases are available.', 5, 'Configure antivirus and endpoint protection tools for automatic signature updates. Verify updates are being applied on all systems daily. Set up alerting for systems that fall behind on updates.'),
  ('3.14.5', 'System and Information Integrity', 'SI', 1, 'Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.', 3, 'Configure your endpoint protection to run full system scans at least weekly. Enable real-time scanning for all file downloads, email attachments, and external media. Review scan reports weekly.'),
  ('3.14.6', 'System and Information Integrity', 'SI', 2, 'Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.', 5, 'Implement email security controls including spam filtering, malware scanning, and phishing detection (e.g., Microsoft Defender for Office 365). Configure DMARC, DKIM, and SPF records to prevent email spoofing.'),
  ('3.14.7', 'System and Information Integrity', 'SI', 2, 'Identify unauthorized use of organizational systems.', 3, 'Deploy a web content filter to block access to known malicious websites. Maintain a category-based blocklist. Review blocked site logs weekly and update policies as needed.')
on conflict (id) do update set
  domain = excluded.domain,
  domain_code = excluded.domain_code,
  level = excluded.level,
  description = excluded.description,
  weight = excluded.weight,
  guidance = excluded.guidance;

update assessment_responses set control_id = case control_id
    when 'AC.1.001' then '3.1.1'
    when 'AC.1.002' then '3.1.2'
    when 'AC.2.003' then '3.1.3'
    when 'AC.2.004' then '3.1.4'
    when 'AC.2.007' then '3.1.5'
    when 'AC.2.008' then '3.1.6'
    when 'AC.2.009' then '3.1.7'
    when 'AC.2.010' then '3.1.8'
    when 'AC.2.005' then '3.1.9'
    when 'AC.2.011' then '3.1.10'
    when 'AC.2.012' then '3.1.11'
    when 'AC.2.013' then '3.1.12'
    when 'AC.2.014' then '3.1.13'
    when 'AC.2.015' then '3.1.14'
    when 'AC.2.016' then '3.1.15'
    when 'AC.2.017' then '3.1.16'
    when 'AC.2.018' then '3.1.17'
    when 'AC.2.019' then '3.1.18'
    when 'AC.2.020' then '3.1.19'
    when 'AC.2.021' then '3.1.20'
    when 'AC.2.006' then '3.1.21'
    when 'AC.2.022' then '3.1.22'
    when 'AT.2.056' then '3.2.1'
    when 'AT.2.057' then '3.2.2'
    when 'AT.3.058' then '3.2.3'
    when 'AU.2.042' then '3.3.1'
    when 'AU.2.041' then '3.3.2'
    when 'AU.2.043' then '3.3.3'
    when 'AU.2.044' then '3.3.4'
    when 'AU.2.045' then '3.3.5'
    when 'AU.2.046' then '3.3.6'
    when 'AU.2.047' then '3.3.7'
    when 'AU.3.046' then '3.3.8'
    when 'AU.3.045' then '3.3.9'
    when 'CM.2.061' then '3.4.1'
    when 'CM.2.062' then '3.4.2'
    when 'CM.2.063' then '3.4.3'
    when 'CM.2.064' then '3.4.4'
    when 'CM.2.065' then '3.4.5'
    when 'CM.3.071' then '3.4.6'
    when 'CM.3.068' then '3.4.7'
    when 'CM.3.069' then '3.4.8'
    when 'CM.3.072' then '3.4.9'
    when 'IA.1.076' then '3.5.1'
    when 'IA.1.077' then '3.5.2'
    when 'IA.3.083' then '3.5.3'
    when 'IA.3.084' then '3.5.4'
    when 'IA.3.085' then '3.5.5'
    when 'IA.3.086' then '3.5.6'
    when 'IA.2.078' then '3.5.7'
    when 'IA.2.079' then '3.5.8'
    when 'IA.2.080' then '3.5.9'
    when 'IA.2.081' then '3.5.10'
    when 'IA.2.082' then '3.5.11'
    when 'IR.2.092' then '3.6.1'
    when 'IR.2.093' then '3.6.2'
    when 'IR.2.094' then '3.6.3'
    when 'MA.2.111' then '3.7.1'
    when 'MA.2.112' then '3.7.2'
    when 'MA.2.113' then '3.7.3'
    when 'MA.2.114' then '3.7.4'
    when 'MA.3.115' then '3.7.5'
    when 'MA.3.116' then '3.7.6'
    when 'MP.2.119' then '3.8.1'
    when 'MP.3.126' then '3.8.2'
    when 'MP.1.118' then '3.8.3'
    when 'MP.3.122' then '3.8.4'
    when 'MP.2.120' then '3.8.5'
    when 'MP.3.124' then '3.8.6'
    when 'MP.2.121' then '3.8.7'
    when 'MP.3.123' then '3.8.8'
    when 'MP.3.125' then '3.8.9'
    when 'PS.2.127' then '3.9.1'
    when 'PS.3.128' then '3.9.2'
    when 'PE.1.131' then '3.10.1'
    when 'PE.1.132' then '3.10.2'
    when 'PE.2.133' then '3.10.3'
    when 'PE.2.134' then '3.10.4'
    when 'PE.3.137' then '3.10.5'
    when 'PE.3.136' then '3.10.6'
    when 'RA.2.141' then '3.11.1'
    when 'RA.2.142' then '3.11.2'
    when 'RA.3.144' then '3.11.3'
    when 'CA.2.157' then '3.12.1'
    when 'CA.2.158' then '3.12.2'
    when 'CA.2.159' then '3.12.3'
    when 'CA.3.161' then '3.12.4'
    when 'SC.1.175' then '3.13.1'
    when 'SC.3.180' then '3.13.2'
    when 'SC.3.181' then '3.13.3'
    when 'SC.3.182' then '3.13.4'
    when 'SC.1.176' then '3.13.5'
    when 'SC.3.183' then '3.13.6'
    when 'SC.3.184' then '3.13.7'
    when 'SC.3.185' then '3.13.8'
    when 'SC.3.186' then '3.13.9'
    when 'SC.3.187' then '3.13.10'
    when 'SC.3.177' then '3.13.11'
    when 'SC.2.178' then '3.13.12'
    when 'SC.3.189' then '3.13.13'
    when 'SC.3.190' then '3.13.14'
    when 'SC.3.179' then '3.13.15'
    when 'SC.3.188' then '3.13.16'
    when 'SI.1.210' then '3.14.1'
    when 'SI.1.211' then '3.14.2'
    when 'SI.2.214' then '3.14.3'
    when 'SI.1.212' then '3.14.4'
    when 'SI.1.213' then '3.14.5'
    when 'SI.2.216' then '3.14.6'
    when 'SI.3.218' then '3.14.7'
    else control_id end
  where control_id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');

update remediation_notes set control_id = case control_id
    when 'AC.1.001' then '3.1.1'
    when 'AC.1.002' then '3.1.2'
    when 'AC.2.003' then '3.1.3'
    when 'AC.2.004' then '3.1.4'
    when 'AC.2.007' then '3.1.5'
    when 'AC.2.008' then '3.1.6'
    when 'AC.2.009' then '3.1.7'
    when 'AC.2.010' then '3.1.8'
    when 'AC.2.005' then '3.1.9'
    when 'AC.2.011' then '3.1.10'
    when 'AC.2.012' then '3.1.11'
    when 'AC.2.013' then '3.1.12'
    when 'AC.2.014' then '3.1.13'
    when 'AC.2.015' then '3.1.14'
    when 'AC.2.016' then '3.1.15'
    when 'AC.2.017' then '3.1.16'
    when 'AC.2.018' then '3.1.17'
    when 'AC.2.019' then '3.1.18'
    when 'AC.2.020' then '3.1.19'
    when 'AC.2.021' then '3.1.20'
    when 'AC.2.006' then '3.1.21'
    when 'AC.2.022' then '3.1.22'
    when 'AT.2.056' then '3.2.1'
    when 'AT.2.057' then '3.2.2'
    when 'AT.3.058' then '3.2.3'
    when 'AU.2.042' then '3.3.1'
    when 'AU.2.041' then '3.3.2'
    when 'AU.2.043' then '3.3.3'
    when 'AU.2.044' then '3.3.4'
    when 'AU.2.045' then '3.3.5'
    when 'AU.2.046' then '3.3.6'
    when 'AU.2.047' then '3.3.7'
    when 'AU.3.046' then '3.3.8'
    when 'AU.3.045' then '3.3.9'
    when 'CM.2.061' then '3.4.1'
    when 'CM.2.062' then '3.4.2'
    when 'CM.2.063' then '3.4.3'
    when 'CM.2.064' then '3.4.4'
    when 'CM.2.065' then '3.4.5'
    when 'CM.3.071' then '3.4.6'
    when 'CM.3.068' then '3.4.7'
    when 'CM.3.069' then '3.4.8'
    when 'CM.3.072' then '3.4.9'
    when 'IA.1.076' then '3.5.1'
    when 'IA.1.077' then '3.5.2'
    when 'IA.3.083' then '3.5.3'
    when 'IA.3.084' then '3.5.4'
    when 'IA.3.085' then '3.5.5'
    when 'IA.3.086' then '3.5.6'
    when 'IA.2.078' then '3.5.7'
    when 'IA.2.079' then '3.5.8'
    when 'IA.2.080' then '3.5.9'
    when 'IA.2.081' then '3.5.10'
    when 'IA.2.082' then '3.5.11'
    when 'IR.2.092' then '3.6.1'
    when 'IR.2.093' then '3.6.2'
    when 'IR.2.094' then '3.6.3'
    when 'MA.2.111' then '3.7.1'
    when 'MA.2.112' then '3.7.2'
    when 'MA.2.113' then '3.7.3'
    when 'MA.2.114' then '3.7.4'
    when 'MA.3.115' then '3.7.5'
    when 'MA.3.116' then '3.7.6'
    when 'MP.2.119' then '3.8.1'
    when 'MP.3.126' then '3.8.2'
    when 'MP.1.118' then '3.8.3'
    when 'MP.3.122' then '3.8.4'
    when 'MP.2.120' then '3.8.5'
    when 'MP.3.124' then '3.8.6'
    when 'MP.2.121' then '3.8.7'
    when 'MP.3.123' then '3.8.8'
    when 'MP.3.125' then '3.8.9'
    when 'PS.2.127' then '3.9.1'
    when 'PS.3.128' then '3.9.2'
    when 'PE.1.131' then '3.10.1'
    when 'PE.1.132' then '3.10.2'
    when 'PE.2.133' then '3.10.3'
    when 'PE.2.134' then '3.10.4'
    when 'PE.3.137' then '3.10.5'
    when 'PE.3.136' then '3.10.6'
    when 'RA.2.141' then '3.11.1'
    when 'RA.2.142' then '3.11.2'
    when 'RA.3.144' then '3.11.3'
    when 'CA.2.157' then '3.12.1'
    when 'CA.2.158' then '3.12.2'
    when 'CA.2.159' then '3.12.3'
    when 'CA.3.161' then '3.12.4'
    when 'SC.1.175' then '3.13.1'
    when 'SC.3.180' then '3.13.2'
    when 'SC.3.181' then '3.13.3'
    when 'SC.3.182' then '3.13.4'
    when 'SC.1.176' then '3.13.5'
    when 'SC.3.183' then '3.13.6'
    when 'SC.3.184' then '3.13.7'
    when 'SC.3.185' then '3.13.8'
    when 'SC.3.186' then '3.13.9'
    when 'SC.3.187' then '3.13.10'
    when 'SC.3.177' then '3.13.11'
    when 'SC.2.178' then '3.13.12'
    when 'SC.3.189' then '3.13.13'
    when 'SC.3.190' then '3.13.14'
    when 'SC.3.179' then '3.13.15'
    when 'SC.3.188' then '3.13.16'
    when 'SI.1.210' then '3.14.1'
    when 'SI.1.211' then '3.14.2'
    when 'SI.2.214' then '3.14.3'
    when 'SI.1.212' then '3.14.4'
    when 'SI.1.213' then '3.14.5'
    when 'SI.2.216' then '3.14.6'
    when 'SI.3.218' then '3.14.7'
    else control_id end
  where control_id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');

update artifacts set control_id = case control_id
    when 'AC.1.001' then '3.1.1'
    when 'AC.1.002' then '3.1.2'
    when 'AC.2.003' then '3.1.3'
    when 'AC.2.004' then '3.1.4'
    when 'AC.2.007' then '3.1.5'
    when 'AC.2.008' then '3.1.6'
    when 'AC.2.009' then '3.1.7'
    when 'AC.2.010' then '3.1.8'
    when 'AC.2.005' then '3.1.9'
    when 'AC.2.011' then '3.1.10'
    when 'AC.2.012' then '3.1.11'
    when 'AC.2.013' then '3.1.12'
    when 'AC.2.014' then '3.1.13'
    when 'AC.2.015' then '3.1.14'
    when 'AC.2.016' then '3.1.15'
    when 'AC.2.017' then '3.1.16'
    when 'AC.2.018' then '3.1.17'
    when 'AC.2.019' then '3.1.18'
    when 'AC.2.020' then '3.1.19'
    when 'AC.2.021' then '3.1.20'
    when 'AC.2.006' then '3.1.21'
    when 'AC.2.022' then '3.1.22'
    when 'AT.2.056' then '3.2.1'
    when 'AT.2.057' then '3.2.2'
    when 'AT.3.058' then '3.2.3'
    when 'AU.2.042' then '3.3.1'
    when 'AU.2.041' then '3.3.2'
    when 'AU.2.043' then '3.3.3'
    when 'AU.2.044' then '3.3.4'
    when 'AU.2.045' then '3.3.5'
    when 'AU.2.046' then '3.3.6'
    when 'AU.2.047' then '3.3.7'
    when 'AU.3.046' then '3.3.8'
    when 'AU.3.045' then '3.3.9'
    when 'CM.2.061' then '3.4.1'
    when 'CM.2.062' then '3.4.2'
    when 'CM.2.063' then '3.4.3'
    when 'CM.2.064' then '3.4.4'
    when 'CM.2.065' then '3.4.5'
    when 'CM.3.071' then '3.4.6'
    when 'CM.3.068' then '3.4.7'
    when 'CM.3.069' then '3.4.8'
    when 'CM.3.072' then '3.4.9'
    when 'IA.1.076' then '3.5.1'
    when 'IA.1.077' then '3.5.2'
    when 'IA.3.083' then '3.5.3'
    when 'IA.3.084' then '3.5.4'
    when 'IA.3.085' then '3.5.5'
    when 'IA.3.086' then '3.5.6'
    when 'IA.2.078' then '3.5.7'
    when 'IA.2.079' then '3.5.8'
    when 'IA.2.080' then '3.5.9'
    when 'IA.2.081' then '3.5.10'
    when 'IA.2.082' then '3.5.11'
    when 'IR.2.092' then '3.6.1'
    when 'IR.2.093' then '3.6.2'
    when 'IR.2.094' then '3.6.3'
    when 'MA.2.111' then '3.7.1'
    when 'MA.2.112' then '3.7.2'
    when 'MA.2.113' then '3.7.3'
    when 'MA.2.114' then '3.7.4'
    when 'MA.3.115' then '3.7.5'
    when 'MA.3.116' then '3.7.6'
    when 'MP.2.119' then '3.8.1'
    when 'MP.3.126' then '3.8.2'
    when 'MP.1.118' then '3.8.3'
    when 'MP.3.122' then '3.8.4'
    when 'MP.2.120' then '3.8.5'
    when 'MP.3.124' then '3.8.6'
    when 'MP.2.121' then '3.8.7'
    when 'MP.3.123' then '3.8.8'
    when 'MP.3.125' then '3.8.9'
    when 'PS.2.127' then '3.9.1'
    when 'PS.3.128' then '3.9.2'
    when 'PE.1.131' then '3.10.1'
    when 'PE.1.132' then '3.10.2'
    when 'PE.2.133' then '3.10.3'
    when 'PE.2.134' then '3.10.4'
    when 'PE.3.137' then '3.10.5'
    when 'PE.3.136' then '3.10.6'
    when 'RA.2.141' then '3.11.1'
    when 'RA.2.142' then '3.11.2'
    when 'RA.3.144' then '3.11.3'
    when 'CA.2.157' then '3.12.1'
    when 'CA.2.158' then '3.12.2'
    when 'CA.2.159' then '3.12.3'
    when 'CA.3.161' then '3.12.4'
    when 'SC.1.175' then '3.13.1'
    when 'SC.3.180' then '3.13.2'
    when 'SC.3.181' then '3.13.3'
    when 'SC.3.182' then '3.13.4'
    when 'SC.1.176' then '3.13.5'
    when 'SC.3.183' then '3.13.6'
    when 'SC.3.184' then '3.13.7'
    when 'SC.3.185' then '3.13.8'
    when 'SC.3.186' then '3.13.9'
    when 'SC.3.187' then '3.13.10'
    when 'SC.3.177' then '3.13.11'
    when 'SC.2.178' then '3.13.12'
    when 'SC.3.189' then '3.13.13'
    when 'SC.3.190' then '3.13.14'
    when 'SC.3.179' then '3.13.15'
    when 'SC.3.188' then '3.13.16'
    when 'SI.1.210' then '3.14.1'
    when 'SI.1.211' then '3.14.2'
    when 'SI.2.214' then '3.14.3'
    when 'SI.1.212' then '3.14.4'
    when 'SI.1.213' then '3.14.5'
    when 'SI.2.216' then '3.14.6'
    when 'SI.3.218' then '3.14.7'
    else control_id end
  where control_id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');

update control_ai_feedback set control_id = case control_id
    when 'AC.1.001' then '3.1.1'
    when 'AC.1.002' then '3.1.2'
    when 'AC.2.003' then '3.1.3'
    when 'AC.2.004' then '3.1.4'
    when 'AC.2.007' then '3.1.5'
    when 'AC.2.008' then '3.1.6'
    when 'AC.2.009' then '3.1.7'
    when 'AC.2.010' then '3.1.8'
    when 'AC.2.005' then '3.1.9'
    when 'AC.2.011' then '3.1.10'
    when 'AC.2.012' then '3.1.11'
    when 'AC.2.013' then '3.1.12'
    when 'AC.2.014' then '3.1.13'
    when 'AC.2.015' then '3.1.14'
    when 'AC.2.016' then '3.1.15'
    when 'AC.2.017' then '3.1.16'
    when 'AC.2.018' then '3.1.17'
    when 'AC.2.019' then '3.1.18'
    when 'AC.2.020' then '3.1.19'
    when 'AC.2.021' then '3.1.20'
    when 'AC.2.006' then '3.1.21'
    when 'AC.2.022' then '3.1.22'
    when 'AT.2.056' then '3.2.1'
    when 'AT.2.057' then '3.2.2'
    when 'AT.3.058' then '3.2.3'
    when 'AU.2.042' then '3.3.1'
    when 'AU.2.041' then '3.3.2'
    when 'AU.2.043' then '3.3.3'
    when 'AU.2.044' then '3.3.4'
    when 'AU.2.045' then '3.3.5'
    when 'AU.2.046' then '3.3.6'
    when 'AU.2.047' then '3.3.7'
    when 'AU.3.046' then '3.3.8'
    when 'AU.3.045' then '3.3.9'
    when 'CM.2.061' then '3.4.1'
    when 'CM.2.062' then '3.4.2'
    when 'CM.2.063' then '3.4.3'
    when 'CM.2.064' then '3.4.4'
    when 'CM.2.065' then '3.4.5'
    when 'CM.3.071' then '3.4.6'
    when 'CM.3.068' then '3.4.7'
    when 'CM.3.069' then '3.4.8'
    when 'CM.3.072' then '3.4.9'
    when 'IA.1.076' then '3.5.1'
    when 'IA.1.077' then '3.5.2'
    when 'IA.3.083' then '3.5.3'
    when 'IA.3.084' then '3.5.4'
    when 'IA.3.085' then '3.5.5'
    when 'IA.3.086' then '3.5.6'
    when 'IA.2.078' then '3.5.7'
    when 'IA.2.079' then '3.5.8'
    when 'IA.2.080' then '3.5.9'
    when 'IA.2.081' then '3.5.10'
    when 'IA.2.082' then '3.5.11'
    when 'IR.2.092' then '3.6.1'
    when 'IR.2.093' then '3.6.2'
    when 'IR.2.094' then '3.6.3'
    when 'MA.2.111' then '3.7.1'
    when 'MA.2.112' then '3.7.2'
    when 'MA.2.113' then '3.7.3'
    when 'MA.2.114' then '3.7.4'
    when 'MA.3.115' then '3.7.5'
    when 'MA.3.116' then '3.7.6'
    when 'MP.2.119' then '3.8.1'
    when 'MP.3.126' then '3.8.2'
    when 'MP.1.118' then '3.8.3'
    when 'MP.3.122' then '3.8.4'
    when 'MP.2.120' then '3.8.5'
    when 'MP.3.124' then '3.8.6'
    when 'MP.2.121' then '3.8.7'
    when 'MP.3.123' then '3.8.8'
    when 'MP.3.125' then '3.8.9'
    when 'PS.2.127' then '3.9.1'
    when 'PS.3.128' then '3.9.2'
    when 'PE.1.131' then '3.10.1'
    when 'PE.1.132' then '3.10.2'
    when 'PE.2.133' then '3.10.3'
    when 'PE.2.134' then '3.10.4'
    when 'PE.3.137' then '3.10.5'
    when 'PE.3.136' then '3.10.6'
    when 'RA.2.141' then '3.11.1'
    when 'RA.2.142' then '3.11.2'
    when 'RA.3.144' then '3.11.3'
    when 'CA.2.157' then '3.12.1'
    when 'CA.2.158' then '3.12.2'
    when 'CA.2.159' then '3.12.3'
    when 'CA.3.161' then '3.12.4'
    when 'SC.1.175' then '3.13.1'
    when 'SC.3.180' then '3.13.2'
    when 'SC.3.181' then '3.13.3'
    when 'SC.3.182' then '3.13.4'
    when 'SC.1.176' then '3.13.5'
    when 'SC.3.183' then '3.13.6'
    when 'SC.3.184' then '3.13.7'
    when 'SC.3.185' then '3.13.8'
    when 'SC.3.186' then '3.13.9'
    when 'SC.3.187' then '3.13.10'
    when 'SC.3.177' then '3.13.11'
    when 'SC.2.178' then '3.13.12'
    when 'SC.3.189' then '3.13.13'
    when 'SC.3.190' then '3.13.14'
    when 'SC.3.179' then '3.13.15'
    when 'SC.3.188' then '3.13.16'
    when 'SI.1.210' then '3.14.1'
    when 'SI.1.211' then '3.14.2'
    when 'SI.2.214' then '3.14.3'
    when 'SI.1.212' then '3.14.4'
    when 'SI.1.213' then '3.14.5'
    when 'SI.2.216' then '3.14.6'
    when 'SI.3.218' then '3.14.7'
    else control_id end
  where control_id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');

update assessor_determinations set control_id = case control_id
    when 'AC.1.001' then '3.1.1'
    when 'AC.1.002' then '3.1.2'
    when 'AC.2.003' then '3.1.3'
    when 'AC.2.004' then '3.1.4'
    when 'AC.2.007' then '3.1.5'
    when 'AC.2.008' then '3.1.6'
    when 'AC.2.009' then '3.1.7'
    when 'AC.2.010' then '3.1.8'
    when 'AC.2.005' then '3.1.9'
    when 'AC.2.011' then '3.1.10'
    when 'AC.2.012' then '3.1.11'
    when 'AC.2.013' then '3.1.12'
    when 'AC.2.014' then '3.1.13'
    when 'AC.2.015' then '3.1.14'
    when 'AC.2.016' then '3.1.15'
    when 'AC.2.017' then '3.1.16'
    when 'AC.2.018' then '3.1.17'
    when 'AC.2.019' then '3.1.18'
    when 'AC.2.020' then '3.1.19'
    when 'AC.2.021' then '3.1.20'
    when 'AC.2.006' then '3.1.21'
    when 'AC.2.022' then '3.1.22'
    when 'AT.2.056' then '3.2.1'
    when 'AT.2.057' then '3.2.2'
    when 'AT.3.058' then '3.2.3'
    when 'AU.2.042' then '3.3.1'
    when 'AU.2.041' then '3.3.2'
    when 'AU.2.043' then '3.3.3'
    when 'AU.2.044' then '3.3.4'
    when 'AU.2.045' then '3.3.5'
    when 'AU.2.046' then '3.3.6'
    when 'AU.2.047' then '3.3.7'
    when 'AU.3.046' then '3.3.8'
    when 'AU.3.045' then '3.3.9'
    when 'CM.2.061' then '3.4.1'
    when 'CM.2.062' then '3.4.2'
    when 'CM.2.063' then '3.4.3'
    when 'CM.2.064' then '3.4.4'
    when 'CM.2.065' then '3.4.5'
    when 'CM.3.071' then '3.4.6'
    when 'CM.3.068' then '3.4.7'
    when 'CM.3.069' then '3.4.8'
    when 'CM.3.072' then '3.4.9'
    when 'IA.1.076' then '3.5.1'
    when 'IA.1.077' then '3.5.2'
    when 'IA.3.083' then '3.5.3'
    when 'IA.3.084' then '3.5.4'
    when 'IA.3.085' then '3.5.5'
    when 'IA.3.086' then '3.5.6'
    when 'IA.2.078' then '3.5.7'
    when 'IA.2.079' then '3.5.8'
    when 'IA.2.080' then '3.5.9'
    when 'IA.2.081' then '3.5.10'
    when 'IA.2.082' then '3.5.11'
    when 'IR.2.092' then '3.6.1'
    when 'IR.2.093' then '3.6.2'
    when 'IR.2.094' then '3.6.3'
    when 'MA.2.111' then '3.7.1'
    when 'MA.2.112' then '3.7.2'
    when 'MA.2.113' then '3.7.3'
    when 'MA.2.114' then '3.7.4'
    when 'MA.3.115' then '3.7.5'
    when 'MA.3.116' then '3.7.6'
    when 'MP.2.119' then '3.8.1'
    when 'MP.3.126' then '3.8.2'
    when 'MP.1.118' then '3.8.3'
    when 'MP.3.122' then '3.8.4'
    when 'MP.2.120' then '3.8.5'
    when 'MP.3.124' then '3.8.6'
    when 'MP.2.121' then '3.8.7'
    when 'MP.3.123' then '3.8.8'
    when 'MP.3.125' then '3.8.9'
    when 'PS.2.127' then '3.9.1'
    when 'PS.3.128' then '3.9.2'
    when 'PE.1.131' then '3.10.1'
    when 'PE.1.132' then '3.10.2'
    when 'PE.2.133' then '3.10.3'
    when 'PE.2.134' then '3.10.4'
    when 'PE.3.137' then '3.10.5'
    when 'PE.3.136' then '3.10.6'
    when 'RA.2.141' then '3.11.1'
    when 'RA.2.142' then '3.11.2'
    when 'RA.3.144' then '3.11.3'
    when 'CA.2.157' then '3.12.1'
    when 'CA.2.158' then '3.12.2'
    when 'CA.2.159' then '3.12.3'
    when 'CA.3.161' then '3.12.4'
    when 'SC.1.175' then '3.13.1'
    when 'SC.3.180' then '3.13.2'
    when 'SC.3.181' then '3.13.3'
    when 'SC.3.182' then '3.13.4'
    when 'SC.1.176' then '3.13.5'
    when 'SC.3.183' then '3.13.6'
    when 'SC.3.184' then '3.13.7'
    when 'SC.3.185' then '3.13.8'
    when 'SC.3.186' then '3.13.9'
    when 'SC.3.187' then '3.13.10'
    when 'SC.3.177' then '3.13.11'
    when 'SC.2.178' then '3.13.12'
    when 'SC.3.189' then '3.13.13'
    when 'SC.3.190' then '3.13.14'
    when 'SC.3.179' then '3.13.15'
    when 'SC.3.188' then '3.13.16'
    when 'SI.1.210' then '3.14.1'
    when 'SI.1.211' then '3.14.2'
    when 'SI.2.214' then '3.14.3'
    when 'SI.1.212' then '3.14.4'
    when 'SI.1.213' then '3.14.5'
    when 'SI.2.216' then '3.14.6'
    when 'SI.3.218' then '3.14.7'
    else control_id end
  where control_id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');

delete from controls where id in ('AC.1.001', 'AC.1.002', 'AC.2.003', 'AC.2.004', 'AC.2.007', 'AC.2.008', 'AC.2.009', 'AC.2.010', 'AC.2.005', 'AC.2.011', 'AC.2.012', 'AC.2.013', 'AC.2.014', 'AC.2.015', 'AC.2.016', 'AC.2.017', 'AC.2.018', 'AC.2.019', 'AC.2.020', 'AC.2.021', 'AC.2.006', 'AC.2.022', 'AT.2.056', 'AT.2.057', 'AT.3.058', 'AU.2.042', 'AU.2.041', 'AU.2.043', 'AU.2.044', 'AU.2.045', 'AU.2.046', 'AU.2.047', 'AU.3.046', 'AU.3.045', 'CM.2.061', 'CM.2.062', 'CM.2.063', 'CM.2.064', 'CM.2.065', 'CM.3.071', 'CM.3.068', 'CM.3.069', 'CM.3.072', 'IA.1.076', 'IA.1.077', 'IA.3.083', 'IA.3.084', 'IA.3.085', 'IA.3.086', 'IA.2.078', 'IA.2.079', 'IA.2.080', 'IA.2.081', 'IA.2.082', 'IR.2.092', 'IR.2.093', 'IR.2.094', 'MA.2.111', 'MA.2.112', 'MA.2.113', 'MA.2.114', 'MA.3.115', 'MA.3.116', 'MP.2.119', 'MP.3.126', 'MP.1.118', 'MP.3.122', 'MP.2.120', 'MP.3.124', 'MP.2.121', 'MP.3.123', 'MP.3.125', 'PS.2.127', 'PS.3.128', 'PE.1.131', 'PE.1.132', 'PE.2.133', 'PE.2.134', 'PE.3.137', 'PE.3.136', 'RA.2.141', 'RA.2.142', 'RA.3.144', 'CA.2.157', 'CA.2.158', 'CA.2.159', 'CA.3.161', 'SC.1.175', 'SC.3.180', 'SC.3.181', 'SC.3.182', 'SC.1.176', 'SC.3.183', 'SC.3.184', 'SC.3.185', 'SC.3.186', 'SC.3.187', 'SC.3.177', 'SC.2.178', 'SC.3.189', 'SC.3.190', 'SC.3.179', 'SC.3.188', 'SI.1.210', 'SI.1.211', 'SI.2.214', 'SI.1.212', 'SI.1.213', 'SI.2.216', 'SI.3.218');
